if True:
    if True:
        if True:
            if True:
                if True:
                    if True:
                        if True:
                            if True:
                                if True:
                                    if True:
                                        if True:
                                            if True:
                                                if True:
                                                    if True:
                                                        if True:
                                                            if True:
                                                                if True:
                                                                    if True:
                                                                        if True:
                                                                            if True:
                                                                                if True:
                                                                                    if True:
                                                                                        if True:
                                                                                            if True:
                                                                                                if True:
                                                                                                    if True:
                                                                                                        if True:
                                                                                                            if True:
                                                                                                                if True:
                                                                                                                    if True:
                                                                                                                        if True:
                                                                                                                            if True:
                                                                                                                                if True:
                                                                                                                                    if True:
                                                                                                                                        if True:
                                                                                                                                            if True:
                                                                                                                                                if True:
                                                                                                                                                    if True:
                                                                                                                                                        if True:
                                                                                                                                                            if True:
                                                                                                                                                                if True:
                                                                                                                                                                    if True:
                                                                                                                                                                        if True:
                                                                                                                                                                            if True:
                                                                                                                                                                                if True:
                                                                                                                                                                                    if True:
                                                                                                                                                                                        if True:
                                                                                                                                                                                            if True:
                                                                                                                                                                                                if True:
                                                                                                                                                                                                    if True:
                                                                                                                                                                                                        if True:
                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                                                                                                                        if True:
                                                                                                                                                                                                                                                                                                                                                                                            if True:
                                                                                                                                                                                                                                                                                                                                                                                                if True:
                                                                                                                                                                                                                                                                                                                                                                                                    if True:
                                                                                                                                                                                                                                                                                                                                                                                                        import os
                                                                                                                                                                                                                                                                                                                                                                                                        import cv2
                                                                                                                                                                                                                                                                                                                                                                                                        from sklearn.preprocessing import StandardScaler
                                                                                                                                                                                                                                                                                                                                                                                                        from sklearn.model_selection import train_test_split
                                                                                                                                                                                                                                                                                                                                                                                                        import Network as nn
                                                                                                                                                                                                                                                                                                                                                                                                        import pandas as pd
                                                                                                                                                                                                                                                                                                                                                                                                        import numpy as np
                                                                                                                                                                                                                                                                                                                                                                                                        import matplotlib.pyplot as plt
                                                                                                                                                                                                                                                                                                                                                                                                        from activation_function import sigmoid, softmax, relu
                                                                                                                                                                                                                                                                                                                                                                                                        from extract_fruit import ExtractData
                                                                                                                                                                                                                                                                                                                                                                                                        from cost_functions import CE, accuracy
                                                                                                                                                                                                                                                                                                                                                                                                        from numpy import random
                                                                                                                                                                                                                                                                                                                                                                                                        import seaborn as sb
                                                                                                                                                                                                                                                                                                                                                                                                        from tqdm import trange

                                                                                                                                                                                                                                                                                                                                                                                                        path = "../images"

                                                                                                                                                                                                                                                                                                                                                                                                        num_fruits = 2

                                                                                                                                                                                                                                                                                                                                                                                                        apples = ExtractData(path, "Apple", 500)
                                                                                                                                                                                                                                                                                                                                                                                                        apples.gray_scale()
                                                                                                                                                                                                                                                                                                                                                                                                        Apple = apples()
                                                                                                                                                                                                                                                                                                                                                                                                        apple_hot = [[0,1] for i in range(len(Apple))]


                                                                                                                                                                                                                                                                                                                                                                                                        bananas = ExtractData(path, "Banana", 500)
                                                                                                                                                                                                                                                                                                                                                                                                        bananas.gray_scale()
                                                                                                                                                                                                                                                                                                                                                                                                        Banana = bananas()
                                                                                                                                                                                                                                                                                                                                                                                                        banana_hot = [[1,0] for i in range(len(Banana))]

                                                                                                                                                                                                                                                                                                                                                                                                        fruit_list = np.concatenate([Apple, Banana])
                                                                                                                                                                                                                                                                                                                                                                                                        fruit_hot = np.concatenate([apple_hot, banana_hot])

                                                                                                                                                                                                                                                                                                                                                                                                        #splitting and scaling data
                                                                                                                                                                                                                                                                                                                                                                                                        train_fruit, test_fruit, train_label, test_label \
                                                                                                                                                                                                                                                                                                                                                                                                            = train_test_split(fruit_list, fruit_hot, test_size = 0.3)
                                                                                                                                                                                                                                                                                                                                                                                                        scaler = StandardScaler()
                                                                                                                                                                                                                                                                                                                                                                                                        scaler.fit(train_fruit)
                                                                                                                                                                                                                                                                                                                                                                                                        train_fruit = scaler.transform(train_fruit)
                                                                                                                                                                                                                                                                                                                                                                                                        test_fruit = scaler.transform(test_fruit)

                                                                                                                                                                                                                                                                                                                                                                                                        fruit_label_test = np.argmax(test_label, axis=1)

                                                                                                                                                                                                                                                                                                                                                                                                        layer1 = nn.DenseLayer(fruit_list.shape[1], 3000, relu(), Glorot = True)
                                                                                                                                                                                                                                                                                                                                                                                                        #first layer will take all width and height pixels as input
                                                                                                                                                                                                                                                                                                                                                                                                        layer2 = nn.DenseLayer(3000, 1000, relu(), Glorot = True)
                                                                                                                                                                                                                                                                                                                                                                                                        layer3 = nn.DenseLayer(1000, 200, relu(), Glorot = True)
                                                                                                                                                                                                                                                                                                                                                                                                        layer4 = nn.DenseLayer(200, 50, relu(), Glorot = True)
                                                                                                                                                                                                                                                                                                                                                                                                        layer5 = nn.DenseLayer(50, num_fruits, softmax(), Glorot = False)
                                                                                                                                                                                                                                                                                                                                                                                                        layers = [layer1, layer2, layer3, layer4, layer5]

                                                                                                                                                                                                                                                                                                                                                                                                        ce = CE()
                                                                                                                                                                                                                                                                                                                                                                                                        m = train_fruit.shape[0]
                                                                                                                                                                                                                                                                                                                                                                                                        batch = np.arange(0,m)
                                                                                                                                                                                                                                                                                                                                                                                                        epochs = 50
                                                                                                                                                                                                                                                                                                                                                                                                        cost = np.zeros((epochs, 2))   #train is first column test is second
                                                                                                                                                                                                                                                                                                                                                                                                        penalty = 0.5
                                                                                                                                                                                                                                                                                                                                                                                                        eta = 0.00002
                                                                                                                                                                                                                                                                                                                                                                                                        network = nn.NN(layers, ce)
                                                                                                                                                                                                                                                                                                                                                                                                        accuracy_vec = np.zeros((epochs, 2))

                                                                                                                                                                                                                                                                                                                                                                                                        for k in trange(epochs):
                                                                                                                                                                                                                                                                                                                                                                                                            random.shuffle(batch)
                                                                                                                                                                                                                                                                                                                                                                                                            train_fruit_shuffle = train_fruit[batch]
                                                                                                                                                                                                                                                                                                                                                                                                            train_label_shuffle = train_label[batch]
                                                                                                                                                                                                                                                                                                                                                                                                            network.SGD(100, train_fruit_shuffle, train_label_shuffle, eta, penalty)
                                                                                                                                                                                                                                                                                                                                                                                                            fruit_pred_train = np.argmax(network.feedforward(train_fruit_shuffle), axis=1)
                                                                                                                                                                                                                                                                                                                                                                                                            fruit_label_train = np.argmax(train_label_shuffle, axis=1)
                                                                                                                                                                                                                                                                                                                                                                                                            fruit_pred_test = np.argmax(network.feedforward(test_fruit), axis = 1)
                                                                                                                                                                                                                                                                                                                                                                                                            accuracy_vec[k, 0] = accuracy()(fruit_label_train, fruit_pred_train)
                                                                                                                                                                                                                                                                                                                                                                                                            accuracy_vec[k, 1] = accuracy()(fruit_label_test, fruit_pred_test)

                                                                                                                                                                                                                                                                                                                                                                                                        plt.xlabel("Epochs")
                                                                                                                                                                                                                                                                                                                                                                                                        plt.ylabel("accuracy")
                                                                                                                                                                                                                                                                                                                                                                                                        plt.plot(accuracy_vec[:,0], label = "Train accuracy")
                                                                                                                                                                                                                                                                                                                                                                                                        plt.plot(accuracy_vec[:,1], label = "Test accuracy")
                                                                                                                                                                                                                                                                                                                                                                                                        plt.legend()
                                                                                                                                                                                                                                                                                                                                                                                                        plt.show()
